### ISSUE TITLE
Release to production 

### ISSUE THREAD

**Issue by 4nte** [kallefrombosnia/halflife-cmds#2]
I suggest that you deploy to https://zeit.co (now.js)
* Completely free
* Auto deploys a new version when you commit to repo
* You can use custom domains for free or get a *.now.sh for free as well.
* Easy to setup

**Comment by kallefrombosnia** [comment]
I agree with that this should go live. First thought was to deploy it to github pages but [https://zeit.co ](https://zeit.co ) seems better solution.
Thanks 4 the suggestion.
You can visit live version on https://halflife-cmds.now.sh/
